//! The vocabularies a surrogate is drawn from.
//!
//! EVERY POOL IS DELIBERATELY UNEVEN IN LENGTH, and that is the whole design
//! constraint. Property (c) of L5 is that a surrogate must not preserve the
//! shape of the original: if a four-letter name always became a four-letter
//! name, the span map would leak the original's length, and the red team's
//! structural-leakage attack class reconstructs candidate name lists from
//! exactly that. The draw is a keyed-hash index into these pools and never
//! consults the original's length, so decorrelation is a property of the
//! construction rather than of a post-hoc filter. `mod.rs`'s
//! `surrogate_length_does_not_correlate_with_original_length` measures it.
//!
//! All entries are ordinary Turkish vocabulary, synthetic in the sense that
//! matters: no entry is taken from a real record (I8). A draw that happens to
//! collide with a medical-allowlist term is regenerated by the caller, because
//! a surrogate that reads as `Adalat` or `Deva` would be masked-then-kept as
//! vocabulary by a downstream L4 and would corrupt the note.

/// Given names, 2 to 9 characters, in no length order.
pub(super) const GIVEN_NAMES: [&str; 48] = [
    "Ada",
    "Ali",
    "Aslı",
    "Ayşegül",
    "Bahar",
    "Berk",
    "Beyzanur",
    "Burcu",
    "Can",
    "Cemre",
    "Cihangir",
    "Defne",
    "Demet",
    "Ece",
    "Efe",
    "Elif",
    "Emine",
    "Ercüment",
    "Esra",
    "Fatmagül",
    "Ferhunde",
    "Gizem",
    "Gökhan",
    "Gülbahar",
    "Hakan",
    "Hilal",
    "Hüseyin",
    "Işıl",
    "Kerem",
    "Kudret",
    "Lale",
    "Mehmet",
    "Melis",
    "Mert",
    "Necmettin",
    "Nur",
    "Onur",
    "Pınar",
    "Selin",
    "Serkan",
    "Sevilay",
    "Su",
    "Şevket",
    "Tuğçe",
    "Umut",
    "Yağmur",
    "Zehra",
    "Zeynep",
];

/// Surnames, 2 to 11 characters.
pub(super) const SURNAMES: [&str; 48] = [
    "Ak",
    "Akgündüz",
    "Alkan",
    "Altınbaşak",
    "Arslanoğlu",
    "Aydın",
    "Bal",
    "Başaran",
    "Bilgin",
    "Büyükkaya",
    "Çelik",
    "Çetinkaya",
    "Dalkıran",
    "Demir",
    "Doğanay",
    "Duran",
    "Ekşi",
    "Erdoğmuş",
    "Ergin",
    "Gül",
    "Güneş",
    "Gürsoy",
    "Işık",
    "Kahraman",
    "Kara",
    "Karadağ",
    "Kavuncu",
    "Kılıçarslan",
    "Koç",
    "Korkmaz",
    "Kurtuluş",
    "Ok",
    "Öz",
    "Özdemirci",
    "Sarıkaya",
    "Sezer",
    "Söylemez",
    "Şahin",
    "Şimşek",
    "Tan",
    "Taşdelen",
    "Toprak",
    "Uçar",
    "Uzunoğlu",
    "Yalçınkaya",
    "Yavuz",
    "Yıldırım",
    "Yurdakul",
];

/// Provinces and large districts, 3 to 16 characters.
pub(super) const CITIES: [&str; 32] = [
    "Adana",
    "Afyonkarahisar",
    "Ankara",
    "Antalya",
    "Aydın",
    "Balıkesir",
    "Bolu",
    "Bursa",
    "Çanakkale",
    "Denizli",
    "Diyarbakır",
    "Edirne",
    "Erzurum",
    "Eskişehir",
    "Gaziantep",
    "Iğdır",
    "İstanbul",
    "İzmir",
    "Kahramanmaraş",
    "Kayseri",
    "Kocaeli",
    "Konya",
    "Malatya",
    "Manisa",
    "Muş",
    "Nevşehir",
    "Rize",
    "Samsun",
    "Şanlıurfa",
    "Tekirdağ",
    "Trabzon",
    "Van",
];

/// Neighbourhood and district names, 3 to 13 characters.
pub(super) const DISTRICTS: [&str; 24] = [
    "Akçalar",
    "Bağlarbaşı",
    "Bahçelievler",
    "Cumhuriyet",
    "Çamlıca",
    "Değirmenlik",
    "Esentepe",
    "Fatih",
    "Gültepe",
    "Hürriyet",
    "Işıklar",
    "Karşıyaka",
    "Kavaklıdere",
    "Kordon",
    "Merkez",
    "Ovacık",
    "Pazar",
    "Selimiye",
    "Söğütlü",
    "Şirinyer",
    "Tepebaşı",
    "Ulus",
    "Yenimahalle",
    "Zafer",
];

/// Street names, deliberately of mixed word count as well as mixed length.
pub(super) const STREETS: [&str; 20] = [
    "Ihlamur",
    "Menekşe",
    "Zambak",
    "Gül",
    "Karanfil",
    "Papatya",
    "Yeşilyurt",
    "Barbaros",
    "Sakarya",
    "Çınarlı",
    "Fevzi Çakmak",
    "Şehit Onbaşı",
    "Kuyumcular",
    "Değirmen",
    "Hasanağa",
    "Bostancı",
    "Uzunçarşı",
    "Kavaklı",
    "Adliye",
    "İnönü",
];

/// Hospital and clinic name stems.
pub(super) const FACILITY_STEMS: [&str; 16] = [
    "Yeşilova",
    "Çamlık",
    "Batı",
    "Kuzey",
    "Gökdere",
    "Akpınar",
    "Sarıçam",
    "Beyaz Zambak",
    "Tunaeli",
    "Karaburun",
    "Bahçeşehir",
    "Yenidoğan",
    "Deniz",
    "Umut",
    "Yıldızkent",
    "Alacaköy",
];

/// The tail of a facility name, chosen independently of the stem so the
/// surrogate's total length varies for reasons unrelated to the original's.
pub(super) const FACILITY_KINDS: [&str; 6] = [
    "Devlet Hastanesi",
    "Eğitim ve Araştırma Hastanesi",
    "Tıp Merkezi",
    "Poliklinigi",
    "Aile Sağlığı Merkezi",
    "Özel Hastanesi",
];

/// Email domains, none of them a real institution.
pub(super) const EMAIL_DOMAINS: [&str; 8] = [
    "ornek.com",
    "ornek.com.tr",
    "posta.example",
    "eposta.example.tr",
    "mail.ornek.net",
    "kurum.example",
    "test.example.org",
    "ileti.example.tr",
];

/// Mobile network prefixes actually allocated in Turkey.
///
/// Real prefixes rather than invented ones, because property (a) is that a
/// downstream validator still accepts the output, and Turkish phone validators
/// commonly check the operator prefix as well as the length. The subscriber
/// digits after the prefix are drawn uniformly, so no real subscriber is
/// targeted by construction of the prefix list.
pub(super) const MOBILE_PREFIXES: [&str; 24] = [
    "501", "505", "506", "507", "530", "531", "532", "533", "534", "535", "536", "537", "538",
    "539", "541", "542", "543", "544", "545", "546", "551", "552", "553", "555",
];

/// Landline area codes.
pub(super) const AREA_CODES: [&str; 12] = [
    "212", "216", "224", "232", "242", "262", "312", "322", "332", "342", "352", "462",
];

/// Five-digit bank codes for the IBAN body. Padded to the fixed width the
/// format demands; the mod-97 check digits are computed over whatever lands
/// here, so no entry needs to correspond to a real institution.
pub(super) const BANK_CODES: [&str; 10] = [
    "00061", "00010", "00012", "00015", "00032", "00046", "00062", "00064", "00067", "00111",
];

/// Turkish licence-plate letter groups.
pub(super) const PLATE_LETTERS: [&str; 12] = [
    "AB", "BC", "CD", "EF", "GH", "JK", "ABC", "DEF", "GHJ", "KLM", "NPR", "STU",
];
