"""The Rust corpus measurement must walk the same fixtures the eval harness walks.

WHY THIS TEST EXISTS. `core/src/route/mod.rs::corpus_measurement` embeds the corpus with
`include_str!`, which needs literal paths, so it carries a HARDCODED list. The eval harness
(`eval/build_gold.py`) DISCOVERS fixtures with `rglob("*.jsonl")`. Those two disagree the moment
somebody adds a fixture file, and they disagreed silently for a full session: `adv_unicode.jsonl`
added 12 documents, the harness moved to 190, and the Rust measurement stayed on 178 while its
number was quoted in `docs/COMPARISON.md` and `docs/DECISIONS.md` next to harness numbers from the
larger corpus.

Nothing failed. Both sides were internally correct and the published rate just quietly described a
different corpus than the benchmark beside it.

The measurement cannot glob, because `include_str!` is compile-time and `core/` performs no runtime
I/O (I1). So the drift is caught here instead, where reading the filesystem is ordinary, and it is
caught by comparing the two lists rather than by trusting either.
"""

from __future__ import annotations

import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
ROUTE_MOD = REPO_ROOT / "core" / "src" / "route" / "mod.rs"
FIXTURE_ROOTS = (REPO_ROOT / "eval" / "gold", REPO_ROOT / "eval" / "adversarial")

# Matches the path inside `include_str!("../../../eval/gold/gold_001_020.jsonl")`.
_INCLUDE = re.compile(r'include_str!\(\s*"\.\./\.\./\.\./(eval/[^"]+\.jsonl)"\s*\)')


def _embedded_fixtures() -> set[str]:
    """Fixture paths the Rust measurement embeds, repo-relative."""
    return set(_INCLUDE.findall(ROUTE_MOD.read_text(encoding="utf-8")))


def _discovered_fixtures() -> set[str]:
    """Fixture paths on disk, discovered the way eval/build_gold.py discovers them."""
    found: set[str] = set()
    for root in FIXTURE_ROOTS:
        for path in root.rglob("*.jsonl"):
            # `.build/` holds resolved offsets generated by build_gold.py, not fixtures.
            if ".build" in path.parts:
                continue
            found.add(path.relative_to(REPO_ROOT).as_posix())
    return found


def test_every_fixture_on_disk_is_embedded_in_the_rust_measurement() -> None:
    """A new fixture file must reach the escalation measurement, not just the harness.

    This is the direction that actually caused the drift. A fixture added to the corpus raises the
    document count the harness reports; if it is not also embedded here, the escalation rate keeps
    describing the old, smaller corpus while being published beside the new numbers.
    """
    missing = _discovered_fixtures() - _embedded_fixtures()
    assert not missing, (
        "fixture files exist on disk but are not embedded in "
        f"core/src/route/mod.rs::corpus_measurement::CORPUS: {sorted(missing)}. "
        "Add an include_str! line for each, then re-run "
        "`cargo test -p deid-tr-core corpus_measurement -- --nocapture` and update any published "
        "escalation figure that moved. The measurement cannot glob (include_str! is compile-time "
        "and core/ does no runtime I/O), so this list is maintained by hand and drifts silently."
    )


def test_every_embedded_fixture_still_exists() -> None:
    """The reverse direction: a renamed or deleted fixture must not leave a stale include.

    This one fails at compile time rather than here, since `include_str!` on a missing path is a
    hard error. It is asserted anyway so the failure names the cause instead of surfacing as an
    opaque build break.
    """
    absent = _embedded_fixtures() - _discovered_fixtures()
    assert not absent, (
        "core/src/route/mod.rs embeds fixture paths that no longer exist: "
        f"{sorted(absent)}. Note the golden set is append-only (I7): a fixture that vanished was "
        "probably renamed, and renaming a fixture still loses its history."
    )


def test_the_two_sides_are_the_same_set() -> None:
    """Belt and braces: state the invariant itself, so the intent survives a refactor."""
    assert _embedded_fixtures() == _discovered_fixtures()
